// Declare the data1 array
export let data1 = [
  {
    id: "01",
    name: "Chicken Burger",
    img: "https://drive.google.com/file/d/1qs1F3eFPGOPByS4axHCzHkM8LWT52OSy/view?usp=sharing",
    category: "Burger",
    price: 24.0,
    quantity: 0,
  },
  {
    id: "02",
    name: "Vegetarian Pizza",
    img: "https://drive.google.com/file/d/1qs1F3eFPGOPByS4axHCzHkM8LWT52OSy/view?usp=sharing",
    category: "Pizza",
    price: 115.0,
    quantity: 0,
  },
  {
    id: "03",
    name: "Double Cheese Margherita",
    img: "https://drive.google.com/file/d/1qs1F3eFPGOPByS4axHCzHkM8LWT52OSy/view?usp=sharing",
    category: "Pizza",
    price: 110.0,
    quantity: 0,
  },
  {
    id: "04",
    name: "Maxican Green Wave",
    img: "https://drive.google.com/file/d/1qs1F3eFPGOPByS4axHCzHkM8LWT52OSy/view?usp=sharing",
    category: "Pizza",
    price: 110.0,
    quantity: 0,
  },
  {
    id: "05",
    name: "Cheese Burger",
    img: "https://drive.google.com/file/d/1qs1F3eFPGOPByS4axHCzHkM8LWT52OSy/view?usp=sharing",
    category: "Burger",
    price: 24.0,
    quantity: 0,
  },
  {
    id: "06",
    name: "Royal Cheese Burger",
    img: "https://drive.google.com/file/d/1qs1F3eFPGOPByS4axHCzHkM8LWT52OSy/view?usp=sharing",
    category: "Burger",
    price: 24.0,
    quantity: 0,
  },
  {
    id: "07",
    name: "Seafood Pizza",
    img: "https://drive.google.com/file/d/1qs1F3eFPGOPByS4axHCzHkM8LWT52OSy/view?usp=sharing",
    category: "Pizza",
    price: 115.0,
    quantity: 0,
  },
  {
    id: "08",
    name: "Thin Cheese Pizza",
    img: "https://drive.google.com/file/d/1zbvnprh7EZxH-1RJDbwdReSRT7Uq9nuM/view?usp=sharing",
    category: "Pizza",
    price: 110.0,
    quantity: 0,
  },
  {
    id: "09",
    name: "Pizza With Mushroom",
    img: "https://drive.google.com/file/d/1-Lx4t5yH8HBJkERrOKVc97cO1x-reo1J/view?usp=sharing",
    category: "Pizza",
    price: 110.0,
    quantity: 0,
  },
  {
    id: "10",
    name: "Classic Hamburger",
    img: "https://drive.google.com/file/d/1qs1F3eFPGOPByS4axHCzHkM8LWT52OSy/view?usp=sharing",
    category: "Burger",
    price: 24.0,
    quantity: 0,
  },
  {
    id: "11",
    name: "Crunchy Bread ",
    img: "https://drive.google.com/file/d/1qs1F3eFPGOPByS4axHCzHkM8LWT52OSy/view?usp=sharing",
    category: "Bread",
    price: 35.0,
    quantity: 0,
  },
  {
    id: "12",
    name: "Delicious Bread ",
    img: "https://drive.google.com/file/d/1qs1F3eFPGOPByS4axHCzHkM8LWT52OSy/view?usp=sharing",
    category: "Bread",
    price: 35.0,
    quantity: 0,
  },
  {
    id: "13",
    name: "Loaf Bread ",
    img: "https://drive.google.com/file/d/1qs1F3eFPGOPByS4axHCzHkM8LWT52OSy/view?usp=sharing",
    category: "Bread",
    price: 35.0,
    quantity: 0,
  },
];

// Export the data1 array
export { data1 };
